### ISSUE TITLE
Invoice Module issues

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1461]
ENV: PROD
Please fix below mentioned bugs ASAP.

1. User is unable to search invoices by invoice number. This is because invoice number is not being passed in get all vouchers API request.
PFA screenshot.

2. User is unable to preview generated invoices from 2nd page. This is because even after getting response from API, Get all vouchers API is being called repeatedly and loader is displayed on page. PFA screenshot.

**Comment by sagarnankani** [comment]
Checked on Test.
Point 1 is FIXED

**Comment by mustafa-walkover** [comment]
point 2 Deployed on test, please test

**Comment by Eagle-Giddh** [comment]
Point 2 is working but it is showing an error.
Please check the screen shot for reference.
![Screenshot 2018-12-05 at 1.29.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c078f1798e7720011e7d8c9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7951e32a64c5b266ed1b3553564f2ed153444d04bea6d37ef5f22e7a98595aebd1640e73943d14a4eb8019bf01b325884e81b1bfd85edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cf542e84456a7153761e1647b.png)

**Comment by Eagle-Giddh** [comment]
Fixed and working fine

**Comment by Eagle-Giddh** [comment]
not fixed please check the attached file.
[Uploading Screenshot 2018-12-13 at 3.22.05 PM.png...]

**Comment by mustafa-walkover** [comment]
@Eagle-Giddh as per the discussion, if template is not exsit, default template design will be shown
